# Generated by Django 5.1.7 on 2025-04-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
